version: '3.8'
services:
  email-template-builder-db:
    container_name: email-template-builder-db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  email-template-builder-be:
    container_name: email-template-builder-be
    build: .
    ports:
      - 3000:3000
    depends_on:
      - email-template-builder-db
    env_file: ./.env.docker
    volumes:
      - .:/usr/src/app
      - be_node_modules:/usr/src/app/node_modules
      - uploads:/usr/src/app/uploads

  email-template-builder-fe:
    container_name: email-template-builder-fe
    build: ../email-template-builder-fe
    ports:
      - 8080:8080
    depends_on:
      - email-template-builder-be
    env_file: ../email-template-builder-fe/.env
    volumes:
      - ../email-template-builder-fe:/usr/src/app
      - fe_node_modules:/usr/src/app/node_modules

volumes:
  mongodb_data_container:
  uploads:
  be_node_modules:
  fe_node_modules:
